# SITE CONFIGURATION
# baseurl: "/"
url: "https://assay.github.io/"
title: Software Assay # site's title
description: "Software Assay" # used by search engines

defaults:
  - 
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: assets/img/logo.png # seo tag

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  avatar: assets/img/logo.png # logomakr.com/95Stya
  color_image: /assets/img/lineart.png # In post when you set color
  favicon: assets/img/favicon.png

  # Header and footer text
  header_text: <p align="right"><br></p>
  header_feature_image: assets/img/pexels/header.jpg
  footer_text: >
    Based on <a href="https://github.com/nettle/white-type">White Type</a> theme

# PAGINATION
paginate: 50
paginate_path: "blog/page:num"

# AUTHORS
authors:
  nettle: # author-id
    name: Alex
    avatar: "assets/img/avatars/nettle.png"
    url:
  some-name: # author-id
    name: Red Sun Bonsai
    avatar: "assets/img/avatars/red-sun-bonsai.png"
    url:

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "*.gem",
          "LICENSE", "README.md"]
# theme: white-type # Uncomment if using the theme as a jekyll theme gem
